---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: LoadBalancer
  selector:
    app: bloodbank
  ports:
  - protocol: TCP
    port: 3000                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
